# Generated by Django 3.1.5 on 2021-02-08 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255, unique=True)),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('refresh_token', models.CharField(max_length=255)),
                ('access_token', models.CharField(max_length=255)),
                ('expires_in', models.DateTimeField()),
                ('token_type', models.CharField(max_length=255)),
            ],
        ),
    ]
