# Generated by Django 3.1.5 on 2021-02-09 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=3, max_length=7, unique=True)),
                ('host', models.CharField(max_length=255, unique=True)),
                ('can_pause', models.BooleanField(default=False)),
                ('vote_to_skip', models.IntegerField(default=0)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
