# Generated by Django 3.1.5 on 2021-02-09 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontCode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default='', max_length=7, unique=True),
        ),
    ]
