# Generated by Django 3.1.5 on 2021-02-09 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontCode', '0002_auto_20210209_0021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='date_time',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='can_pause',
            new_name='guest_can_pause',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='vote_to_skip',
            new_name='votes_to_skip',
        ),
    ]
