# Generated by Django 3.1.5 on 2021-02-09 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontCode', '0003_auto_20210209_0028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='guest_can_pause',
            new_name='can_pause',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='created_at',
            new_name='date_time',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='votes_to_skip',
            new_name='vote_to_skip',
        ),
    ]
