# Generated by Django 3.1.5 on 2021-02-11 11:48

from django.db import migrations, models
import frontCode.models


class Migration(migrations.Migration):

    dependencies = [
        ('frontCode', '0004_auto_20210209_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=frontCode.models.unique_code, max_length=7, unique=True),
        ),
    ]
