# Generated by Django 3.1.6 on 2021-02-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontCode', '0005_auto_20210211_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='vote_to_skip',
        ),
        migrations.AddField(
            model_name='room',
            name='votes_to_skip',
            field=models.IntegerField(default=1),
        ),
    ]
