# Generated by Django 3.1.5 on 2021-02-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontCode', '0006_auto_20210216_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='votes_to_skip',
        ),
        migrations.AddField(
            model_name='room',
            name='vote_to_skip',
            field=models.IntegerField(default=0),
        ),
    ]
